const express = require('express');
const router = express.Router();
const auth = require('../middleware/authMiddleware');
const DailyConcept = require('../models/DailyConcept');

// Static topic rotation for placeholder generation
const TOPIC_ROTATION = [
    { subject: 'DSA', topic: 'Arrays & Hashing' },
    { subject: 'Backend', topic: 'REST API Design' },
    { subject: 'Aptitude', topic: 'Time and Work' },
    { subject: 'Core CS', topic: 'Operating Systems Basics' },
    { subject: 'DSA', topic: 'Two Pointers' },
    { subject: 'Backend', topic: 'Database Normalization' },
    { subject: 'Aptitude', topic: 'Percentages' }
];

// GET /api/today
router.get('/today', auth, async (req, res) => {
    try {
        // 1. Get today's date adjusted to start of day (UTC or local)
        const today = new Date();
        today.setHours(0, 0, 0, 0);

        // 2. Check if DailyConcept exists for today
        let concept = await DailyConcept.findOne({ date: today });

        if (concept) {
            return res.json(concept);
        }

        // 3. If not exists, create a placeholder one based on rotation
        // Simple rotation based on day of month to pick a topic
        const dayIndex = today.getDate() % TOPIC_ROTATION.length;
        const selectedTopic = TOPIC_ROTATION[dayIndex];

        concept = new DailyConcept({
            date: today,
            subject: selectedTopic.subject,
            topic: selectedTopic.topic,
            difficulty: "Medium",
            summary: `Today we are focusing on ${selectedTopic.topic} in ${selectedTopic.subject}. This is a crucial concept for placement interviews.`,
            explanation: `
                <h3>Understanding ${selectedTopic.topic}</h3>
                <p>This concept is fundamental to solving efficient problems. In interviews, you will often be asked to demonstrate this.</p>
                <ul>
                    <li>Key Principle 1: Efficiency</li>
                    <li>Key Principle 2: Scalability</li>
                    <li>Key Principle 3: Edge Case Handling</li>
                </ul>
                <p>Detailed explanation will be generated by the AI engine in the next phase. For now, focus on the structure.</p>
            `,
            codeExample: {
                language: "javascript",
                code: `// Sample implementation for ${selectedTopic.topic}\n\nfunction solve(input) {\n  // Implementation logic here\n  return result;\n}`
            },
            quiz: [
                {
                    question: `What is the primary benefit of ${selectedTopic.topic}?`,
                    options: ["Efficiency", "Complexity", "Redundancy", "Styles"],
                    correctAnswer: "Efficiency"
                },
                {
                    question: "Which complexity class does this typically fall into?",
                    options: ["O(1)", "O(n)", "O(n^2)", "O(log n)"],
                    correctAnswer: "O(n)"
                },
                {
                    question: " True or False: This is commonly asked in FAANG interviews?",
                    options: ["True", "False"],
                    correctAnswer: "True"
                }
            ]
        });

        await concept.save();
        res.json(concept);

    } catch (err) {
        console.error(err.message);
        res.status(500).send('Server Error');
    }
});

module.exports = router;
